### ISSUE TITLE
Closing brace on new line

### ISSUE THREAD

**Issue by juanfraa** [keegnotrub/coda-sass-plugin#11]
Hey there!

Great plugin, the only problem I find is that using the Nested Output style I get the closing brace for each class beside the last property instead of a new line.

Also, I'm used to do tabbing to have a nested code and the plugin uses two blank spaces.

Have you thought about adding some options to configure this in the future?

![screen shot 2014-07-25 at 12 54 15 pm](https://cloud.githubusercontent.com/assets/252415/3704448/11668cca-1414-11e4-900b-04bf6440c32b.png)
![screen shot 2014-07-25 at 12 54 32 pm](https://cloud.githubusercontent.com/assets/252415/3704449/116c5a74-1414-11e4-85a7-474836de186c.png)

Thanks,
Juan.

**Comment by keegnotrub** [comment]
@juanfraa this should now be available in the latest release

https://github.com/keegnotrub/coda-sass-plugin/releases/tag/v3.1.0

**Comment by juanfraa** [comment]
Awesome! you rock @keegnotrub! Thanks.
