### ISSUE TITLE
Using random() function

### ISSUE THREAD

**Issue by davorpeic** [keegnotrub/coda-sass-plugin#19]
Hi,

thank for the great plugin, I'm trying to use random($limit) to get random number but its not working :( 

Any ideas?

Thank you!
Davor

**Comment by keegnotrub** [comment]
Hi @davorpeic - `random` wasn't supported in libsass (the library this plugin uses to compile the sass into css) until just recently (16 days ago it looks like).  When I get a second I'll attempt to update the libsass version to 3.1 and do a new release.

Thanks for the feedback!

**Comment by davorpeic** [comment]
Yeah, I found out that while doing my research :) at the moment I'm using just plain $ sass --watch

thanks

**Comment by keegnotrub** [comment]
@davorpeic this should now be available in the latest release

https://github.com/keegnotrub/coda-sass-plugin/releases/tag/v3.1.0
