### ISSUE TITLE
Some Bourbon Mixins missing.

### ISSUE THREAD

**Issue by chrisfromthelc** [keegnotrub/coda-sass-plugin#21]
I was struggling with using a mixin, and then realized that Bourbon is a bit outdated. It looks like **selection** was added a few days after Bourbon was added to the plugin. I'm sure there are probably more missing that I haven't found yet.

**Comment by keegnotrub** [comment]
Thanks for reporting this.  The versions of the included libraries can be found here:

https://github.com/keegnotrub/coda-sass-plugin/wiki/Included-Sass-Libraries

I'll be updating the plugin to the latest versions when I update libsass soon.

**Comment by chrisfromthelc** [comment]
I was able to update the plugin on my local machine in the meantime.

(Thanks for doing this plugin, by the way. It fits perfectly into my
workflow!)

**Comment by keegnotrub** [comment]
@chrisfromthelc  this should now be available in the latest release

https://github.com/keegnotrub/coda-sass-plugin/releases/tag/v3.1.0
