### ISSUE TITLE
Coda now crashes when I hit save

### ISSUE THREAD

**Issue by purenine** [keegnotrub/coda-sass-plugin#27]
Hey, plugin was great but now when I hit save, coda crashes and nothing gets saved or compiled to css. Can you help?

Error attached
![screen shot 2015-07-28 at 11 12 21 am](https://cloud.githubusercontent.com/assets/3288080/8935203/87f2b022-3519-11e5-81a3-959d16ed1690.png)

Can also send you the real error txt file if you need it.

Thanks!

Tom

**Comment by keegnotrub** [comment]
Thanks, would you be able to send me the sass you are compiling as well so that I might try to replicate it on my side for testing?

**Comment by purenine** [comment]
Sure, where should I email?

**Comment by keegnotrub** [comment]
Could you just link to a [gist](https://gist.github.com)?

**Comment by purenine** [comment]
I'm new to this, can I send you the stuff via zip?

Tklinger at pure9studios dot com

**Comment by keegnotrub** [comment]
No problem, can you try [this new release](https://github.com/keegnotrub/coda-sass-plugin/releases/tag/v3.1.1) to see if it addressed your issue?  After downloading, unzip and double click the plugin to install.  Be sure though to restart Coda just to be sure you are running the updated plugin after installing.

**Comment by purenine** [comment]
worked! What was the issue?

**Comment by keegnotrub** [comment]
I believe it was an issue with a segfault in libsass when using the min/max function with a literal.  I'll close this issue for now but feel free to reopen if it becomes an issue again.

**Comment by purenine** [comment]
Thanks so much!

Thomas Klinger
914.290.4161
@purenine
