### ISSUE TITLE
Doesn't seem to work when I save .scss file

### ISSUE THREAD

**Issue by showcasefloyd** [keegnotrub/coda-sass-plugin#28]
Question. Do I need to install libsass first to get this to work? I'm working on a MacBook Pro with OS X 10.9.5 running

**Comment by keegnotrub** [comment]
Nope, libsass is bundled with the plugin.  You sometimes need to restart Coda after installing but afterwards you should be able to just create a `scss` file and on save it should generate the `css` file.

If that isn't the case feel free to reply and re-open this issue.

**Comment by showcasefloyd** [comment]
Yup, your right I just needed to restart my Coda2. Should have tried that first. Thanks for making this. It rocks
