### ISSUE TITLE
Compress option

### ISSUE THREAD

**Issue by ghost** [keegnotrub/coda-sass-plugin#31]
Is there a way to compress the output .css file on the most compressed option, but keep comments in tact? I use this for a lot of wordpress builds where the comments area is required at the top.

**Comment by keegnotrub** [comment]
I believe in Sass if you use `/*! My comment */` (note the exclamation point) it will keep the comment.  If that doesn't work feel free to re-open this ticket and let me know.

**Comment by ghost** [comment]
My apologies. I should have caught that. Thanks again
