### ISSUE TITLE
Source map broken link

### ISSUE THREAD

**Issue by miller2287** [keegnotrub/coda-sass-plugin#32]
On my site, I have a /css folder, and all the Sass files are in /css/scss. 

When I save style.scss (in /css/scss) it generates style.css and style.map and outputs to the /css folder (which is fine) but the source map is linked to "../style.map".

<img width="188" alt="screen shot 2016-06-06 at 4 02 48 pm" src="https://cloud.githubusercontent.com/assets/8107169/15835930/596e7b9e-2c00-11e6-83cd-450b4b0a042b.png">

<img width="286" alt="screen shot 2016-06-06 at 4 02 26 pm" src="https://cloud.githubusercontent.com/assets/8107169/15835899/29c95d46-2c00-11e6-810b-19834f633fa5.png">

**Comment by knorthfield** [comment]
Yep, same here. Version 3.1.2

**Comment by andywarren** [comment]
I don't even have a source map being generated. Just installed this in Coda today, seems like its not working as intended. It won't even install v3.1.2, stuck on v3.1.1. I'm a bit confused with it.
